version: '3.5'

volumes:
  data:
    external: true

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - data:/var/lib/postgresql/data
    