version: '3.5'

volumes:
  data:
    external: true


services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - data:/var/lib/postgresql/data

  zookeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
  
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeper:2181
      - KAFKA_CREATE_TOPICS=createuser:1:1, find-all-users:1:1 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    